
spring:
  #
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
server:
  port: 8090

#≈‰÷√
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath:mybatis/mapper/*.xml

  # π”√¡¥Ω”≥ÿdruid